
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-rolebinding
  namespace: nginx-27074
subjects:
  - kind: ServiceAccount
    name: nginx-sa
    namespace: nginx-27074
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io
    